# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - id: sni
    main: ./cmd/sni/
    binary: sni
    goos:
      - windows
      - linux
      - darwin
    ignore: # M1 builds fail currently
      - goos: darwin
        goarch: arm64
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: x86
      amd64: x64
    files:
      - LICENSE*
      - README*
      - protos/sni/sni.proto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  disable: false
  prerelease: auto
  draft: false
